version: '3'
services:
  streamlit_app:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    runtime: nvidia  # Use the NVIDIA runtime to access the GPU
